root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/web"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd", "internal", "ui"]
include_ext = ["go", "tpl", "tmpl", "html", "css"]
include_file = []
kill_delay = "2s"  # Add a delay before killing the previous instance
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = ["./tmp/main"]  # Run the binary only after a successful build
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true  # Gracefully interrupt the previous process
stop_on_error = true  # Stop running if there's an error

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
